version: "3.8"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/test_project
    environment:
      DB_NAME: ${DB_NAME}
      HOST_ADDRESS: ${HOST_ADDRESS}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TYPE: ${TYPE}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
