version: "3.8"
services:
  server:
    build: .
    entrypoint: ./entrypoint-server.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/test_project
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
